In [1]:
import pandas as pd
import pickle

absolute_path = r"C:\Users\mehme\becode---\BECODE___PROJECTS\01.IMMOELIZA\02.Data_Analysis\df.pkl"

with open(absolute_path, 'rb') as f:
    df = pickle.load(f)


pd.set_option('display.max_columns', None)

In [2]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
bathroomcount,94891.0,1.107281e+00,8.901510e-01,0.0,1.0,1.0,1.0,145.0
bedroomcount,94891.0,2.621745e+00,1.280973e+00,0.0,2.0,3.0,3.0,39.0
constructionyear,94891.0,1.993183e+03,3.070738e+01,1895.0,1972.0,2000.0,2022.0,2033.0
fireplace,94891.0,2.770547e-02,1.641285e-01,0.0,0.0,0.0,0.0,1.0
furnished,94891.0,1.861083e-02,1.351468e-01,0.0,0.0,0.0,0.0,1.0
garden,94891.0,1.904396e-01,3.926499e-01,0.0,0.0,0.0,0.0,1.0
kitchen,94891.0,1.616824e+00,8.334084e-01,0.0,1.0,1.0,2.0,3.0
livingarea,94891.0,1.511971e+02,1.902368e+03,12.0,90.0,120.0,168.0,452230.0
numberoffacades,94891.0,2.630934e+00,7.773398e-01,1.0,2.0,2.0,3.0,19.0
postalcode,94891.0,5.346704e+03,3.021364e+03,1000.0,2440.0,4980.0,8480.0,9992.0
price,94891.0,3.402746e+05,1.428048e+05,2500.0,239000.0,320000.0,419000.0,773850.0
propertyid,94891.0,1.229481e+07,2.971516e+06,1882546.0,11118654.5,11363393.0,11460649.5,20025859.0
roomcount,94891.0,5.947266e+00,3.487714e+00,1.0,4.0,5.0,8.0,68.0
showercount,94891.0,8.165685e-01,4.932185e+00,0.0,0.0,1.0,1.0,1120.0
stateofbuilding,94891.0,3.713945e+00,1.062795e+00,0.0,4.0,4.0,4.0,5.0
surfaceofplot,94891.0,5.979610e+02,2.408537e+03,0.0,168.0,313.0,581.0,366356.0
swimmingpool,94891.0,9.916641e-03,9.908786e-02,0.0,0.0,0.0,0.0,1.0
terrace,94891.0,5.750282e-01,4.943413e-01,0.0,0.0,1.0,1.0,1.0
toiletcount,94891.0,4.168470e+01,1.244097e+04,0.0,1.0,1.0,2.0,3832365.0
typeofproperty,94891.0,1.492249e+00,4.999426e-01,1.0,1.0,1.0,2.0,2.0

In [3]:
display(df.shape)
Q1 = df['bathroomcount'].quantile(0.1)
Q3 = df['bathroomcount'].quantile(0.90)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
print(lower_bound, upper_bound)
df = df[(df['bathroomcount'] > lower_bound) & (df['bathroomcount'] < upper_bound)]
display(df.shape)

(94891, 24)

-0.5 3.5

(94201, 24)

In [4]:
display(df.shape)
Q1 = df['bedroomcount'].quantile(0.1)
Q3 = df['bedroomcount'].quantile(0.9)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
print(lower_bound, upper_bound)
df = df[(df['bedroomcount'] > lower_bound) & (df['bedroomcount'] < upper_bound)]
display(df.shape)

(94201, 24)

-3.5 8.5

(94065, 24)

In [5]:
display(df.shape)
Q1 = df['livingarea'].quantile(0.1)
Q3 = df['livingarea'].quantile(0.9)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
print(lower_bound, upper_bound)
df = df[(df['livingarea'] > lower_bound) & (df['livingarea'] < upper_bound)]
display(df.shape)

(94065, 24)

-157.5 446.5

(93380, 24)

In [6]:
import pickle

# pickle.dump(df, open("preprocessor.pkl", "wb"))

with open("after_outlier_df.pkl", "wb") as f:
    pickle.dump(df, f)

In [7]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
bathroomcount,93380.0,1.073827e+00,5.068104e-01,0.0,1.00,1.0,1.00,3.0
bedroomcount,93380.0,2.574898e+00,1.146612e+00,0.0,2.00,3.0,3.00,8.0
constructionyear,93380.0,1.993524e+03,3.056975e+01,1895.0,1973.00,2001.0,2023.00,2033.0
fireplace,93380.0,2.707218e-02,1.622947e-01,0.0,0.00,0.0,0.00,1.0
furnished,93380.0,1.823731e-02,1.338092e-01,0.0,0.00,0.0,0.00,1.0
garden,93380.0,1.886592e-01,3.912398e-01,0.0,0.00,0.0,0.00,1.0
kitchen,93380.0,1.617873e+00,8.338539e-01,0.0,1.00,1.0,2.00,3.0
livingarea,93380.0,1.333340e+02,6.404326e+01,12.0,89.00,118.0,165.00,446.0
numberoffacades,93380.0,2.628507e+00,7.755467e-01,1.0,2.00,2.0,3.00,19.0
postalcode,93380.0,5.346287e+03,3.025425e+03,1000.0,2440.00,4960.0,8490.00,9992.0
price,93380.0,3.377825e+05,1.409532e+05,2500.0,239000.00,319000.0,415000.00,773850.0
propertyid,93380.0,1.229491e+07,2.972118e+06,1882546.0,11118639.75,11363674.5,11461002.75,20025859.0
roomcount,93380.0,5.917830e+00,3.427839e+00,1.0,4.00,5.0,8.00,53.0
showercount,93380.0,8.067038e-01,4.964707e+00,0.0,0.00,1.0,1.00,1120.0
stateofbuilding,93380.0,3.721771e+00,1.055148e+00,0.0,4.00,4.0,4.00,5.0
surfaceofplot,93380.0,5.850302e+02,2.370176e+03,0.0,169.00,312.0,576.00,366356.0
swimmingpool,93380.0,9.573785e-03,9.737674e-02,0.0,0.00,0.0,0.00,1.0
terrace,93380.0,5.764832e-01,4.941183e-01,0.0,0.00,1.0,1.00,1.0
toiletcount,93380.0,1.273870e+00,7.096897e+00,0.0,1.00,1.0,2.00,2147.0
typeofproperty,93380.0,1.499047e+00,5.000018e-01,1.0,1.00,1.0,2.00,2.0

In [15]:
df.shape

(93380, 24)